name: CheckHomework

on: [pull_request]

jobs:
  check:
    if: contains(github.repository,'HackYourFuture')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - name: Echo week folder and run tests
        run: |
          echo ${{github.repository}}
          echo ${{github.ref}}
          export WEEK=$(echo ${{github.ref}} | sed -E 's/.*w(eek)?[-_]?([0-9]).*/week\2/gi')
          echo Week: ${WEEK}
          npm run test-${WEEK}
